"""empty message

Revision ID: 404261474979
Revises: ce118668e369
Create Date: 2022-02-18 11:49:43.641997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404261474979'
down_revision = 'ce118668e369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('eisenhower_id', sa.Integer(), nullable=False))
    op.drop_constraint('tasks_eisenhower_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'eisenhowers', ['eisenhower_id'], ['id'])
    op.drop_column('tasks', 'eisenhower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('eisenhower', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_eisenhower_fkey', 'tasks', 'eisenhowers', ['eisenhower'], ['id'])
    op.drop_column('tasks', 'eisenhower_id')
    # ### end Alembic commands ###
