"""empty message

Revision ID: c93ca88f80bd
Revises: 266ae1d449f5
Create Date: 2022-02-17 17:43:29.235640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93ca88f80bd'
down_revision = '266ae1d449f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.add_column('tasks_categories', sa.Column('category_ide', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'tasks_categories', ['id'])
    op.drop_constraint('tasks_categories_category_id_fkey', 'tasks_categories', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_categories', 'categories', ['category_ide'], ['id'])
    op.drop_column('tasks_categories', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_categories', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks_categories', type_='foreignkey')
    op.create_foreign_key('tasks_categories_category_id_fkey', 'tasks_categories', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'tasks_categories', type_='unique')
    op.drop_column('tasks_categories', 'category_ide')
    op.drop_constraint(None, 'tasks', type_='unique')
    # ### end Alembic commands ###
