"""empty message

Revision ID: ce118668e369
Revises: 21c8ec4fe802
Create Date: 2022-02-18 11:43:44.165828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce118668e369'
down_revision = '21c8ec4fe802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_categories', sa.Column('task_id', sa.Integer(), nullable=True))
    op.add_column('tasks_categories', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_categories_task_fkey', 'tasks_categories', type_='foreignkey')
    op.drop_constraint('tasks_categories_category_fkey', 'tasks_categories', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_categories', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'tasks_categories', 'categories', ['category_id'], ['id'])
    op.drop_column('tasks_categories', 'category')
    op.drop_column('tasks_categories', 'task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_categories', sa.Column('task', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks_categories', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks_categories', type_='foreignkey')
    op.drop_constraint(None, 'tasks_categories', type_='foreignkey')
    op.create_foreign_key('tasks_categories_category_fkey', 'tasks_categories', 'categories', ['category'], ['id'])
    op.create_foreign_key('tasks_categories_task_fkey', 'tasks_categories', 'tasks', ['task'], ['id'])
    op.drop_column('tasks_categories', 'category_id')
    op.drop_column('tasks_categories', 'task_id')
    # ### end Alembic commands ###
