"""empty message

Revision ID: e986d6ca9568
Revises: c93ca88f80bd
Create Date: 2022-02-17 17:44:50.784429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e986d6ca9568'
down_revision = 'c93ca88f80bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_categories', sa.Column('task', sa.Integer(), nullable=True))
    op.add_column('tasks_categories', sa.Column('category', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_categories_category_ide_fkey', 'tasks_categories', type_='foreignkey')
    op.drop_constraint('tasks_categories_task_id_fkey', 'tasks_categories', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_categories', 'tasks', ['task'], ['id'])
    op.create_foreign_key(None, 'tasks_categories', 'categories', ['category'], ['id'])
    op.drop_column('tasks_categories', 'category_ide')
    op.drop_column('tasks_categories', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_categories', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks_categories', sa.Column('category_ide', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks_categories', type_='foreignkey')
    op.drop_constraint(None, 'tasks_categories', type_='foreignkey')
    op.create_foreign_key('tasks_categories_task_id_fkey', 'tasks_categories', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key('tasks_categories_category_ide_fkey', 'tasks_categories', 'categories', ['category_ide'], ['id'])
    op.drop_column('tasks_categories', 'category')
    op.drop_column('tasks_categories', 'task')
    # ### end Alembic commands ###
